src/main/java/com/reobotnet/model/ItemPedido.java
package com.reobotnet.model;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name = "item_pedido")
public class ItemPedido implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private Integer quantidade = 1;
	private BigDecimal valorUnitario = BigDecimal.ZERO;
	private Produto produto;
	private Pedido pedido;

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(nullable = false, length = 3)
	public Integer getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "valor_unitario", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorUnitario() {
		return valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	@ManyToOne
	@JoinColumn(name = "produto_id", nullable = false)
	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@ManyToOne
	@JoinColumn(name = "pedido_id", nullable = false)
	public Pedido getPedido() {
		return pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}
	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ItemPedido other = (ItemPedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	//Calcula o valor total dos itens do pedido
	@Transient
	public BigDecimal getValorTotal() {
		return this.getValorUnitario().multiply(new BigDecimal(this.getQuantidade()));
	}

	
	//Verifica de o item do pedido tem um produto associado a ele
	@Transient
	public boolean isProdutoAssociado() {
		return this.getProduto() != null && this.getProduto().getId() != null;
	}
	
	@Transient
	public boolean isEstoqueSuficiente() {
		return this.getPedido().isEmitido() || this.getProduto().getId() == null 
			|| this.getProduto().getQuantidadeEstoque() >= this.getQuantidade(); 
	}
	
	@Transient
	public boolean isEstoqueInsuficiente() {
		return !this.isEstoqueSuficiente();
	}

}

src/main/java/com/reobotnet/model/Pedido.java
package com.reobotnet.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "pedido")
public class Pedido implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private Date dataCriacao;
	private String observacao;
	private BigDecimal valorFrete = BigDecimal.ZERO;
	private BigDecimal valorDesconto = BigDecimal.ZERO;
	private BigDecimal valorTotal = BigDecimal.ZERO;
	private StatusPedido status = StatusPedido.ORCAMENTO;
	private FormaPagamento formaPagamento;
	private Usuario vendedor;
	private Pessoa pessoa;
	private List<ItemPedido> itens = new ArrayList<>();

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", nullable = false)
	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Column(columnDefinition = "text")
	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@NotNull
	@Column(name = "valor_frete", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorFrete() {
		return valorFrete;
	}

	public void setValorFrete(BigDecimal valorFrete) {
		this.valorFrete = valorFrete;
	}

	@NotNull
	@Column(name = "valor_desconto", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorDesconto() {
		return valorDesconto;
	}

	public void setValorDesconto(BigDecimal valorDesconto) {
		this.valorDesconto = valorDesconto;
	}

	@NotNull
	@Column(name = "valor_total", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorTotal() {
		return valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	public StatusPedido getStatus() {
		return status;
	}

	public void setStatus(StatusPedido status) {
		this.status = status;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "forma_pagamento", nullable = false, length = 20)
	public FormaPagamento getFormaPagamento() {
		return formaPagamento;
	}

	public void setFormaPagamento(FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

	@NotNull
	@ManyToOne
	@JoinColumn(name = "vendedor_id", nullable = false)
	public Usuario getVendedor() {
		return vendedor;
	}

	public void setVendedor(Usuario vendedor) {
		this.vendedor = vendedor;
	}

	@NotNull
	@ManyToOne
	@JoinColumn(name = "pessoa_id", nullable = false)
	public Pessoa getPessoa() {
		return pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	// O lazy faz com oq quando carregar o pedido não seja carregado os itens do
	// pedido
	@OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
	public List<ItemPedido> getItens() {
		return itens;
	}

	public void setItens(List<ItemPedido> itens) {
		this.itens = itens;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pedido other = (Pedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	// Server para dizer se um pedido é novo
	@Transient
	public boolean isNovo() {
		return getId() == null;
	}

	@Transient
	public boolean isExistente() {
		return !isNovo();
	}

	// Adiciona um item vazio se o status for orçamento
	public void adicionarItemVazio() {
		if (this.isOrcamento()) {
			Produto produto = new Produto();

			ItemPedido item = new ItemPedido();

			item.setProduto(produto);
			item.setPedido(this);

			this.getItens().add(0, item);

		}

	}

	// Verifica se o status do pedido está em orçamento
	@Transient
	public boolean isOrcamento() {
		return StatusPedido.ORCAMENTO.equals(this.getStatus());
	}

	// Remove um item vazio (primeira linha) antes de salvar
	public void removerItemVazio() {
		ItemPedido primeiroItem = this.getItens().get(0);

		if (primeiroItem != null && primeiroItem.getProduto().getId() == null) {
			this.getItens().remove(0);
		}
	}

	// Verifica se o total do pedido é negativo
	@Transient
	public boolean isValorTotalNegativo() {
		return this.getValorTotal().compareTo(BigDecimal.ZERO) < 0;
	}

	// recalcula o varlor total do pedido
	public void recalcularValorTotal() {

		BigDecimal total = BigDecimal.ZERO;

		total = total.add(this.getValorFrete()).subtract(this.valorDesconto);

		for (ItemPedido item : this.getItens()) {

			if (item.getProduto() != null && item.getProduto().getId() != null) {
				total = total.add(item.getValorTotal());
			}

		}

		this.setValorTotal(total);
	}

	// Calcula o subtotal do pedido
	@Transient
	public BigDecimal getValorSubtotal() {
		return this.getValorTotal().subtract(this.getValorFrete())
				.add(this.getValorDesconto());
	}

	// Verifica se um pedido é emissivel
	@Transient
	public boolean isEmissivel() {
		return this.isExistente() && this.isOrcamento();
	}

	// Verifica se um pedido mão é emissivel
	@Transient
	public boolean isNaoEmissivel() {
		return !this.isEmissivel();
	}

	// Verifica se o pedido está emitido
	@Transient
	public boolean isEmitido() {
		return StatusPedido.EMITIDO.equals(this.getStatus());
	}
	
	//Verifica se um pedido pode ser cancelado
	@Transient
	public boolean isCancelavel() {
		return this.isExistente() && !this.isCancelado();
	}

	//Verifica se um pedido está cancelado
	@Transient
	private boolean isCancelado() {
		return StatusPedido.CANCELADO.equals(this.getStatus());
	}

	//Diz que um pedido não pode ser cancelado
	@Transient
	public boolean isNaoCancelavel() {
		return !this.isCancelavel();
	}

}

src/main/webapp/WEB-INF/templates/pedidos/BotoesPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<p:toolbar style="margin-top: 20px">
  		<p:toolbarGroup>
  			<p:button value="Novo" outcome="/pedidos/CadastroPedido"/>
  			<p:commandButton value="Salvar" action="#{cadastroPedidoBean.salvar}"
  				 />
  		</p:toolbarGroup>
  		
  		<p:toolbarGroup align="right">
  			<p:commandButton value="Emitir" action="#{emissaoPedidoBean.emitirPedido}" 
  				process="@form" update="@form" />
  			<p:commandButton value="Cancelar" action="#{cancelamentoPedidoBean.cancelarPedido}"
  				process="@this" update="@form" />
  			
  			<p:separator/>
  		
  			<p:button value="Pesquisa" outcome="/pedidos/PesquisaPedidos" />
  		</p:toolbarGroup>
  	</p:toolbar>
  	
</ui:composition>

src/main/webapp/WEB-INF/templates/pedidos/CapaPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<p:panelGrid columns="4" style="width: 100%; margin-top: 20px"
		columnClasses="rotulo, campo, rotulo, campo">

		<!-- Esse campos só redenriza se não for um novo pedido  -->
		<p:outputLabel value="Número"
			rendered="#{cadastroPedidoBean.pedido.existente}" />
		<h:outputText value="#{cadastroPedidoBean.pedido.id}"
			rendered="#{cadastroPedidoBean.pedido.existente}" />

		<!-- Esse campos só redenriza se não for um novo pedido  -->
		<p:outputLabel value="Data de criação"
			rendered="#{cadastroPedidoBean.pedido.existente}" />
		<h:outputText value="#{cadastroPedidoBean.pedido.dataCriacao}"
			rendered="#{cadastroPedidoBean.pedido.existente}">
			<f:convertDateTime pattern="dd/MM/yyyy" />
		</h:outputText>

		<p:outputLabel value="Status" />
		<h:outputText value="#{cadastroPedidoBean.pedido.status.descricao}" />

		<p:outputLabel value="Vendedor" for="vendedor" />
		<p:selectOneMenu id="vendedor"
			value="#{cadastroPedidoBean.pedido.vendedor}">
			<f:selectItem itemLabel="Selecione" />
			<f:selectItems value="#{cadastroPedidoBean.vendedores}"
				var="vendedor" itemValue="#{vendedor}" itemLabel="#{vendedor.nome}" />
		</p:selectOneMenu>

		<p:outputLabel value="Cliente" for="pessoa" />
		<p:selectOneMenu value="#{cadastroPedidoBean.pedido.pessoa}"
			id="pessoa" filter="true" filterMatchMode="contains">
			<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
			<f:selectItems value="#{cadastroPedidoBean.todasPessoas}"
				var="pessoa" itemValue="#{pessoa}" itemLabel="#{pessoa.nome}" />
		</p:selectOneMenu>

		<p:outputLabel value="Forma de pagamento" for="formaPagamento" />
		<p:selectOneMenu id="formaPagamento"
			value="#{cadastroPedidoBean.pedido.formaPagamento}">
			<f:selectItem itemLabel="Selecione" />
			<f:selectItems value="#{cadastroPedidoBean.formasPagamento}"
				var="formaPagamento" itemValue="#{formaPagamento}"
				itemLabel="#{formaPagamento.descricao}" />
		</p:selectOneMenu>

		<p:outputLabel value="Valor do frete" for="valorFrete" />
		<p:inputText id="valorFrete" size="10" maxlength="10"
			styleClass="moeda" value="#{cadastroPedidoBean.pedido.valorFrete}">
			<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
           
            <!-- Alterar o campo totalPedido e recalcula o pedido sempre que processar este campos  -->
			<p:ajax event="change" process="@this" update="totalPedido"
				listener="#{cadastroPedidoBean.recalcularPedido}" />
		</p:inputText>

		<p:outputLabel value="Subtotal" style="font-weight: bold" />
		<h:outputText value="#{cadastroPedidoBean.pedido.valorSubtotal}"
			style="font-weight: bold" id="subtotal">
			<f:convertNumber type="currency" />
		</h:outputText>

		<p:outputLabel value="Valor de desconto" for="valorDesconto" />
		<p:inputText id="valorDesconto" size="10" maxlength="10"
			styleClass="moeda" value="#{cadastroPedidoBean.pedido.valorDesconto}">
			<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
		
			<!-- Alterar o campo totalPedido e recalcula o pedido sempre que processar este campos  -->
			<p:ajax event="change" process="@this" update="totalPedido"
				listener="#{cadastroPedidoBean.recalcularPedido}" />
		</p:inputText>

		<p:outputLabel value="Total do pedido"
			style="font-weight: bold; font-size: 1.1em" />
		<h:outputText value="#{cadastroPedidoBean.pedido.valorTotal}"
			style="font-weight: bold; font-size: 1.1em" id="totalPedido">
			<f:convertNumber type="currency" />
		</h:outputText>
	</p:panelGrid>

</ui:composition>

src/main/webapp/WEB-INF/templates/pedidos/DadosEntregaPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    
    
	
  	
</ui:composition>

src/main/webapp/WEB-INF/templates/pedidos/ItensPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<p:dataTable value="#{cadastroPedidoBean.pedido.itens}" var="item" rowIndexVar="linha"
		id="tabelaItens">
		
		<p:column headerText="SKU" style="text-align: center; width: 100px">
			<h:outputText value="#{item.produto.sku}"
				rendered="#{item.produtoAssociado}" />

			<p:inputText size="8" value="#{cadastroPedidoBean.sku}" label="SKU"
				rendered="#{not item.produtoAssociado}">
				<p:ajax event="change" process="@this"
					update="tabelaItens :frmCadastro:totalPedido :frmCadastro:subtotal"
					listener="#{cadastroPedidoBean.carregarProdutoPorSku}" />
			</p:inputText>
		</p:column>
		
		<p:column headerText="Produto">
			<h:outputText value="#{item.produto.nome}"
				rendered="#{item.produtoAssociado}" />

			<p:autoComplete styleClass="produto-tabela"
				value="#{cadastroPedidoBean.produtoLinhaEditavel}"
				completeMethod="#{cadastroPedidoBean.completarProduto}"
				var="produto" itemLabel="#{produto.nome}" itemValue="#{produto}"
				forceSelection="true" rendered="#{not item.produtoAssociado}">
				<p:ajax event="itemSelect"
					update="tabelaItens :frmCadastro:totalPedido :frmCadastro:subtotal"
					listener="#{cadastroPedidoBean.carregarProdutoLinhaEditavel}" />
			</p:autoComplete>
		</p:column>
		<p:column headerText="Valor unitário"
			style="text-align: right; width: 120px">
			<h:outputText value="#{item.valorUnitario}">
				<f:convertNumber type="currency" />
			</h:outputText>
		</p:column>
		
		<p:column headerText="Quantidade"
			style="text-align: center; width: 100px">
			<p:inputText size="8" value="#{item.quantidade}">
				<p:ajax event="change" process="@this"
					update="tabelaItens :frmCadastro:totalPedido :frmCadastro:subtotal"
					listener="#{cadastroPedidoBean.atualizarQuantidade(item , linha)}" />
			</p:inputText>
		</p:column>
		
		<p:column headerText="Estoque"
			style="text-align: center; width: 100px">
			<h:outputText value="#{item.produto.quantidadeEstoque}" 
				style="#{item.estoqueInsuficiente ? 'color: red' : ''}"/>
				
				<h:graphicImage library="reobotnet" name="/images/alerta.png" id="semEstoque"
				style="vertical-align: bottom; margin-left: 5px" 
				rendered="#{item.estoqueInsuficiente}" />
				
			<p:tooltip for="semEstoque" value="Estoque insuficiente"
				rendered="#{item.estoqueInsuficiente}" />
		</p:column>
		<p:column headerText="Valor total"
			style="text-align: right; width: 100px">
			<h:outputText value="#{item.valorTotal}">
				<f:convertNumber type="currency" />
			</h:outputText>
		</p:column>

		<p:columnGroup type="footer">
			<p:row>
				<p:column colspan="5" footerText="Subtotal"
					style="text-align: right" />
				<p:column style="text-align: right">
					<f:facet name="footer">
						<h:outputText value="#{cadastroPedidoBean.pedido.valorSubtotal}">
							<f:convertNumber type="currency" />
						</h:outputText>
					</f:facet>
				</p:column>
			</p:row>
		</p:columnGroup>
	</p:dataTable>

</ui:composition>

src/main/webapp/WEB-INF/templates/pedidos/ObservacaoPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<h:panelGroup layout="block" style="padding-right: 10px">
		<p:inputTextarea rows="10" style="width: 100%"
			value="#{cadastroPedidoBean.pedido.observacao}" 
			/>
	</h:panelGroup>

</ui:composition>