src/main/java/com/reobotnet/model/Pessoa.java
package com.reobotnet.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.br.CNPJ;
import org.hibernate.validator.constraints.br.CPF;

@Entity
@Table(name = "pessoa")
public class Pessoa implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private TipoClienteFornecedor tipoclientefornecedor; 
	private Status status;
	private TipoPessoa tipopessoa = TipoPessoa.FISICA;
	private String nome;
    private String cpf;
    private String cnpj;
    private String razaoSocial;
    private String inscricaoEstadual;
    private String telefone;
    private String telefoneFax;
    private String celular;
    private String email;
    private String endereco;
    private String complemento;
    private String bairro;
    private String cep;
    private String cidade;
    private String estado;

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	public TipoClienteFornecedor getTipoclientefornecedor() {
		return tipoclientefornecedor;
	}

	public void setTipoclientefornecedor(TipoClienteFornecedor tipoclientefornecedor) {
		this.tipoclientefornecedor = tipoclientefornecedor;
	}
	
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	public TipoPessoa getTipopessoa() {
		return tipopessoa;
	}

	public void setTipopessoa(TipoPessoa tipopessoa) {
		this.tipopessoa = tipopessoa;
	}

	@NotEmpty
	@Size(max = 60)
	@Column(length = 60, nullable = false)
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	
	@CPF
	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}
	
	@CNPJ
	public String getCnpj() {
		return cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	public String getRazaoSocial() {
		return razaoSocial;
	}

	public void setRazaoSocial(String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	public String getInscricaoEstadual() {
		return inscricaoEstadual;
	}

	public void setInscricaoEstadual(String inscricaoEstadual) {
		this.inscricaoEstadual = inscricaoEstadual;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public String getTelefoneFax() {
		return telefoneFax;
	}

	public void setTelefoneFax(String telefoneFax) {
		this.telefoneFax = telefoneFax;
	}

	public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String endereo) {
		this.endereco = endereo;
	}

	public String getComplemento() {
		return complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getCep() {
		return cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public String getCidade() {
		return cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}


	@Transient
	public boolean isFisica() {
		return TipoPessoa.FISICA.equals(this.getTipopessoa());
			
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pessoa other = (Pessoa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/reobotnet/controller/CadastroPessoaBean.java
package com.reobotnet.controller;

import java.io.Serializable;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;


import com.reobotnet.model.Pessoa;
import com.reobotnet.model.Status;
import com.reobotnet.model.TipoClienteFornecedor;
import com.reobotnet.model.TipoPessoa;
import com.reobotnet.service.CadastroPessoaService;
import com.reobotnet.service.NegocioException;



@Named
@ViewScoped
public class CadastroPessoaBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	private CadastroPessoaService cadastroPessoaService;
	
			
	private Pessoa pessoa;
	

	public void prepararCadastro() {
		if (this.pessoa == null) {
			this.pessoa = new Pessoa();
		}
	}
	
			
	public void salvar() {
		FacesContext context = FacesContext.getCurrentInstance();
		
		try {
			this.cadastroPessoaService.salvar(this.pessoa);
			
			this.pessoa = new Pessoa();
			context.addMessage(null, new FacesMessage("Pessoa salva com sucesso!"));
		} catch (NegocioException e) {
			
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}


	public Pessoa getPessoa() {
		return pessoa;
	}


	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}
	
	public TipoClienteFornecedor[] getTipoClienteFornecedores() {
		return TipoClienteFornecedor.values();
	}
	
	public TipoPessoa[] getTipoPessoa() {
		return TipoPessoa.values();
	}
	
	public Status[] getStatus() {
		return Status.values();
	}
	
	
	
}

src/main/java/com/reobotnet/controller/PesquisaPessoasBean.java
package com.reobotnet.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.reobotnet.model.Pessoa;
import com.reobotnet.repository.Pessoas;



@Named
@ViewScoped
public class PesquisaPessoasBean implements Serializable{

	
	private static final long serialVersionUID = 1L;
	
	@Inject
	Pessoas pessoas;
	
	private List<Pessoa> pessoasList = new ArrayList<>();
	
	
	
	public List<Pessoa> getProdutosList() {
		return pessoasList;
	}
	
		
	public Pessoas getPessoas() {
		return pessoas;
	}


	public void setPessoas(Pessoas pessoas) {
		this.pessoas = pessoas;
	}


	public void setPessoasList(List<Pessoa> pessoasList) {
		this.pessoasList = pessoasList;
	}



	@PostConstruct
	public void inicializar() {
		 pessoasList = pessoas.todas();
	}
	
}

src/main/webapp/pessoas/CadastroPessoa.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui"
	template="/WEB-INF/templates/Layout.xhtml">

	<ui:define name="content">
		<h1 class="aw-page-title">Pessoas</h1>

		<f:metadata>
			<o:viewParam name="pessoas" value="#{cadastroPessoaBean.pessoa}" />
		</f:metadata>


		<h:form id="frm">
			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:button value="Novo" />
					<p:commandButton value="Salvar" id="botaoSalvar"
						action="#{cadastroPessoaBean.salvar}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Pesquisa" />
				</p:toolbarGroup>
			</p:toolbar>
			<p:messages showDetail="false" showSummary="true" autoUpdate="true" />

			<p:tabView scrollable="true">
				<p:tab title="Cadastro">
					<h:panelGrid columns="4" columnClasses="label, value">



						<p:outputLabel value="Tipo Cliente / Fornecedor" for="tipo" />

						<p:selectOneMenu id="tipo"
							value="#{cadastroPessoaBean.pessoa.tipoclientefornecedor}">
							<f:selectItems
								value="#{cadastroPessoaBean.tipoClienteFornecedores}"
								var="tipoclientefornecedor" itemValue="#{tipoclientefornecedor}"
								itemLabel="#{tipoclientefornecedor.descricao}" />

						</p:selectOneMenu>

						<p:outputLabel value="Status" for="status" />

						<p:selectOneMenu id="status"
							value="#{cadastroPessoaBean.pessoa.status}">
							<f:selectItems value="#{cadastroPessoaBean.status}" var="status"
								itemValue="#{status}" itemLabel="#{status.descricao}" />

						</p:selectOneMenu>
						
						<p:outputLabel value="Tipo pessoa" for="tipopessoa" />

						<p:selectOneMenu id="tipopessoa"
							value="#{cadastroPessoaBean.pessoa.tipopessoa}">
							<f:selectItems value="#{cadastroPessoaBean.tipoPessoa}" var="tipopessoa"
								itemValue="#{tipopessoa}" itemLabel="#{tipopessoa.descricao}" />
								
									<p:ajax listener="#{cadastroPessoaBean.pessoa.tipopessoa.descricao}" update=":frm" /> 

						</p:selectOneMenu>
						



						<p:outputLabel value="Nome" for="nome" />
						<p:autoComplete id="nome" size="60"
							value="#{cadastroPessoaBean.pessoa.nome}" />

                      
						<p:outputLabel value="Cpf" for="cpf" 
						rendered="#{cadastroPessoaBean.pessoa.fisica}" />
						<p:inputText id="cpf" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.cpf}" 
							rendered="#{cadastroPessoaBean.pessoa.fisica}" />


						<p:outputLabel value="Razão Social" for="razaosocial" />
						<p:inputText id="razaosocial" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.razaoSocial}" />


						<p:outputLabel value="Inscrição Estadual" for="inscricaoestadual" />
						<p:inputText id="inscricaoestadual" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.inscricaoEstadual}" />


						<p:outputLabel value="Cnpj" for="cnpj" />
						<p:inputText id="cnpj" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.cnpj}" />

						<p:outputLabel value="Telefone" for="telefone" />
						<p:inputText id="telefone" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.telefone}" />


						<p:outputLabel value="Fax" for="fax" />
						<p:inputText id="fax" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.telefoneFax}" />


						<p:outputLabel value="Celular" for="celular" />
						<p:inputText id="celular" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.celular}" />


						<p:outputLabel value="E-mail" for="email" />
						<p:inputText id="email" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.email}" />


					</h:panelGrid>
				</p:tab>
				<p:tab title="Endereço">
					<h:panelGrid columns="4" columnClasses="label, value">
					
						<p:outputLabel value="Endereço" for="endereco" />
						<p:inputText id="endereco" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.endereco}" />
						
						<p:outputLabel value="Complemento" for="complemento" />
						<p:inputText id="complemento" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.complemento}" />

						<p:outputLabel value="Bairro" for="bairro" />
						<p:inputText id="bairro" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.bairro}" />

						<p:outputLabel value="Cep" for="cep" />
						<p:inputText id="cep" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.cep}" />

						<p:outputLabel value="Cidade" for="cidade" />
						<p:inputText id="cidade" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.cidade}" />

						<p:outputLabel value="Estado" for="estado" />
						<p:inputText id="estado" maxlength="80"
							value="#{cadastroPessoaBean.pessoa.estado}" />

					</h:panelGrid>
				</p:tab>
			</p:tabView>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/pessoas/PesquisaPessoas.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/Layout.xhtml">

	<ui:define name="content">
		<style type="text/css">
.colored {
	background-color: #FF0000;
	color: #FFFFFF;
}
</style>
		<h:form id="frmPesquisa">
			<h1>Pesquisa de pessoas</h1>

			<p:messages autoUpdate="true" closable="true" />

			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:commandButton value="Pesquisar" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Novo" outcome="/pessoas/CadastroPessoa" />
				</p:toolbarGroup>
				

			</p:toolbar>

			<p:dataTable id="pessoasTable"
				value="#{pesquisaPessoasBean.pessoasList}"
				var="pessoas" style="margin-top: 20px"
				emptyMessage="Nenhum produto encontrado." rows="20" paginator="true"
				paginatorAlwaysVisible="false" paginatorPosition="bottom">
				
								
				<p:column headerText="Status" style="text-align: center"
					sortBy="#{pessoas.status}" width="100">
					<h:outputText value="#{pessoas.status}"/>
						
				</p:column>
				
								
				<p:column filterBy="#{pessoas.nome}" headerText="Nome"
					filterMatchMode="contains" style="text-align: center; width: 120px">
					<h:outputText value="#{pessoas.nome}" />
				</p:column>
								
				
				<p:column style="width: 100px; text-align: center">
					<p:button outcome="/pessoas/CadastroPessoa" icon="ui-icon-pencil"
						title="Editar">
						<f:param name="pessoas" value="#{pessoas.id}" />
					</p:button>
				</p:column>

			</p:dataTable>

			<h:commandLink id="excel">

				<p:graphicImage library="reobotnet" name="images/excel.png" />
				<p:dataExporter type="xls" target="pessoasTable"
					fileName="Pessoas"
					postProcessor="#{customizedDocumentsView.postProcessXLS}" />
			</h:commandLink>
		</h:form>
	</ui:define>
</ui:composition>