src/main/java/com/reobotnet/controller/CadastroLancamentoBean.java
package com.reobotnet.controller;

import java.io.Serializable;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.reobotnet.model.Banco;
import com.reobotnet.model.Custo;
import com.reobotnet.model.FormaPagamento;
import com.reobotnet.model.Lancamento;
import com.reobotnet.model.Pessoa;
import com.reobotnet.model.StatusPagamento;
import com.reobotnet.model.TipoLancamento;
import com.reobotnet.repository.Bancos;
import com.reobotnet.repository.Custos;
import com.reobotnet.repository.LancamentosOld;
import com.reobotnet.repository.Pessoas;
import com.reobotnet.service.CadastroLancamentosService;
import com.reobotnet.service.NegocioException;



@Named
@ViewScoped
public class CadastroLancamentoBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	private CadastroLancamentosService cadastroLancamentosService;
	
	@Inject
	private Pessoas pessoas;
	
	@Inject
	private Custos custos;
	
	@Inject
	private Bancos bancos;
	
	@Inject
	private LancamentosOld lancamentos;
	
	private Lancamento lancamento;
	
	private List<Pessoa> todasPessoas;
	
	private List<Custo>  todosCustos;
	
	private List<Banco> todosBancos;

	public void prepararCadastro() {
		this.todasPessoas = this.pessoas.todas();
		this.todosCustos =  this.custos.buscarTodos();
		this.todosBancos =  this.bancos.buscarTodos();
		
		if (this.lancamento == null) {
			this.lancamento = new Lancamento();
		}
	}
	
	public List<String> pesquisarDescricoes(String descricao) {
		return this.lancamentos.descricoesQueContem(descricao);
	}
	
	public void dataVencimentoAlterada(AjaxBehaviorEvent event) {
		if (this.lancamento.getDataPagamento() == null) {
			this.lancamento.setDataPagamento(this.lancamento.getDataVencimento());
		}
	}
	
	public void salvar() {
		FacesContext context = FacesContext.getCurrentInstance();
		
		try {
			this.cadastroLancamentosService.salvar(this.lancamento);
			
			this.lancamento = new Lancamento();
			context.addMessage(null, new FacesMessage("Lançamento salvo com sucesso!"));
		} catch (NegocioException e) {
			
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}
	
	
		
	public List<Pessoa> getTodasPessoas() {
		return this.todasPessoas;
	}
	
		
	public List<Custo> getTodosCustos() {
		return todosCustos;
	}
	
		
	public List<Banco> getTodosBancos() {
		return todosBancos;
	}

	public TipoLancamento[] getTiposLancamentos() {
		return TipoLancamento.values();
	}
	
	public StatusPagamento[] getStatusPagamento() {
		return StatusPagamento.values();
	}
	
	public FormaPagamento[] getFormaPagamento() {
		return FormaPagamento.values();
	}
	
	public Lancamento getLancamento() {
		return lancamento;
	}

	public void setLancamento(Lancamento lancamento) {
		this.lancamento = lancamento;
	}
	
}

src/main/webapp/financeiro/CadastroCentroDeCusto.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" 
	xmlns:o="http://omnifaces.org/ui"
	template="/WEB-INF/templates/Layout.xhtml">

	<ui:define name="content">
		<h1 class="aw-page-title">Centro de Custo</h1>

		<f:metadata>
			<o:viewParam name="custo" value="#{cadastroCustoBean.custo}" />
		</f:metadata>
		
		<h:form id="frm">
			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:button value="Novo" />
					<p:commandButton value="Salvar" id="botaoSalvar"
						action="#{cadastroCustoBean.salvar}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Pesquisa" outcome="/financeiro/PesquisaCentroDeCusto" />
				</p:toolbarGroup>
			</p:toolbar>

			<p:messages autoUpdate="false" />
			<p:panelGrid columns="2" id="painel"
				style="width: 100%; margin-top: 20px" columnClasses="rotulo, campo">


				<p:outputLabel value="Nome" for="nome" />
				<p:inputText id="nome" size="60" maxlength="80"
					value="#{cadastroCustoBean.custo.nome}" />

			</p:panelGrid>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/financeiro/CadastroLancamento.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui"
	template="/WEB-INF/templates/Layout.xhtml">

	<ui:define name="content">
		<h1 class="aw-page-title">Lançamentos</h1>

		<f:metadata>
			<o:viewParam name="id" value="#{cadastroLancamentoBean.lancamento}" />
			<f:viewAction action="#{cadastroLancamentoBean.prepararCadastro}" />
		</f:metadata>


		<h:form id="frm">
			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:button value="Novo" />
					<p:commandButton value="Salvar" id="botaoSalvar"
						action="#{cadastroLancamentoBean.salvar}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Pesquisa"
						outcome="/financeiro/PesquisaLancamentos" />
				</p:toolbarGroup>
			</p:toolbar>
			<p:messages showDetail="false" showSummary="true" autoUpdate="true" />

			<p:panelGrid style="margin-top: 20px" columns="2" id="grid">

				<p:outputLabel value="Tipo" for="tipo" />
				<p:selectOneButton id="tipo"
					value="#{cadastroLancamentoBean.lancamento.tipo}">
					<f:selectItems value="#{cadastroLancamentoBean.tiposLancamentos}"
						var="tipoLancamento" itemValue="#{tipoLancamento}"
						itemLabel="#{tipoLancamento.descricao}" />
				</p:selectOneButton>


				<p:outputLabel value="Pessoa" for="pessoa" />
				<p:selectOneMenu value="#{cadastroLancamentoBean.lancamento.pessoa}"
					id="pessoa" filter="true" filterMatchMode="contains">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.todasPessoas}"
						var="pessoa" itemValue="#{pessoa}" itemLabel="#{pessoa.nome}" />
				</p:selectOneMenu>

				<p:outputLabel value="Custo" for="custo" />
				<p:selectOneMenu value="#{cadastroLancamentoBean.lancamento.custo}"
					id="custo" filter="true" filterMatchMode="contains">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.todosCustos}"
						var="custo" itemValue="#{custo}" itemLabel="#{custo.nome}" />
				</p:selectOneMenu>

				<p:outputLabel value="Data de emissão" for="dataEmissao" />
				<p:calendar size="12" id="dataEmissao" pattern="dd/MM/yyyy"
					value="#{cadastroLancamentoBean.lancamento.dataEmissao}" />

				<p:outputLabel value="Data de vencimento" for="dataVencimento" />
				<p:calendar id="dataVencimento" size="12" pattern="dd/MM/yyyy"
					value="#{cadastroLancamentoBean.lancamento.dataVencimento}">
					<p:ajax event="dateSelect" update="@this dataPagamento"
						process="@this dataPagamento"
						listener="#{cadastroLancamentoBean.dataVencimentoAlterada}" />
					<p:ajax event="change" update="@this dataPagamento"
						process="@this dataPagamento"
						listener="#{cadastroLancamentoBean.dataVencimentoAlterada}" />
				</p:calendar>

				<p:outputLabel value="Banco" for="banco" />
				<p:selectOneMenu value="#{cadastroLancamentoBean.lancamento.banco}"
					id="banco" filter="true" filterMatchMode="contains">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.todosBancos}"
						var="banco" itemValue="#{banco}" itemLabel="#{banco.nome}" />
				</p:selectOneMenu>

				<p:outputLabel value="Descrição" for="descricao" />
				<p:autoComplete id="descricao" size="60"
					value="#{cadastroLancamentoBean.lancamento.descricao}"
					completeMethod="#{cadastroLancamentoBean.pesquisarDescricoes}" />

				<p:outputLabel value="Nota Fiscal" for="notaFiscal" />
				<p:autoComplete id="notaFiscal" size="20"
					value="#{cadastroLancamentoBean.lancamento.notaFiscal}" />

				<p:outputLabel value="Boleto" for="boleto" />
				<p:autoComplete id="boleto" size="20"
					value="#{cadastroLancamentoBean.lancamento.boleto}" />

				<p:outputLabel value="Juros" for="juros" />
				<p:inputText id="juros" size="12"
					value="#{cadastroLancamentoBean.lancamento.juros}">
					<f:convertNumber locale="pt_BR" maxFractionDigits="2"
						minFractionDigits="2" />
				</p:inputText>

				<p:outputLabel value="Crédito" for="credito" />
				<p:inputText id="credito" size="12"
					value="#{cadastroLancamentoBean.lancamento.credito}">
					<f:convertNumber locale="pt_BR" maxFractionDigits="2"
						minFractionDigits="2" />
				</p:inputText>

				<p:outputLabel value="Valor Pago " for="valorPago" />
				<p:inputText id="valorPago" size="12"
					value="#{cadastroLancamentoBean.lancamento.valorPago}">
					<f:convertNumber locale="pt_BR" maxFractionDigits="2"
						minFractionDigits="2" />
				</p:inputText>
				
				<p:outputLabel value="Valor Recebido " for="valorRecebido" />
				<p:inputText id="valorRecebido" size="12"
					value="#{cadastroLancamentoBean.lancamento.valorRecebido}">
					<f:convertNumber locale="pt_BR" maxFractionDigits="2"
						minFractionDigits="2" />
				</p:inputText>


				<p:outputLabel value="Data de pagamento" for="dataPagamento" />
				<p:calendar size="12" id="dataPagamento" pattern="dd/MM/yyyy"
					value="#{cadastroLancamentoBean.lancamento.dataPagamento}" />

				
				
				<p:outputLabel value="Status pagamento" for="statusPagamento" />
				<p:selectOneMenu value="#{cadastroLancamentoBean.lancamento.statusPagamento}"
					id="statusPagamento" filter="true" filterMatchMode="contains">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.statusPagamento}"
						var="statusPagamento" itemValue="#{statusPagamento}" 
						itemLabel="#{statusPagamento.descricao}" />
				</p:selectOneMenu>
				
				
				<p:outputLabel value="Motivo Cancelamento" for="motivoCancelamento" />
				<p:autoComplete id="motivoCancelamento" size="60"
					value="#{cadastroLancamentoBean.lancamento.motivoCancelamento}"/>
			
				<p:outputLabel value="Forma pagamento" for="formaPagamento" />
				<p:selectOneMenu value="#{cadastroLancamentoBean.lancamento.formaPagamento}"
					id="formaPagamento" filter="true" filterMatchMode="contains">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.formaPagamento}"
						var="formaPagamento" itemValue="#{formaPagamento}" 
						itemLabel="#{formaPagamento.descricao}" />
				</p:selectOneMenu>

				<h:outputLabel />
				<p:commandButton value="Salvar"
					action="#{cadastroLancamentoBean.salvar}" icon="ui-icon-disk"
					update="@form" />
			</p:panelGrid>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/financeiro/CadastroLancamentoEvento.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui"
	template="/WEB-INF/templates/Layout.xhtml">

	<ui:define name="content">
		<h1 class="aw-page-title">Lançamentos</h1>

		<f:metadata>
			<o:viewParam name="id" value="#{cadastroLancamentoBean.lancamento}" />
			<f:viewAction action="#{cadastroLancamentoBean.prepararCadastro}" />
		</f:metadata>


		<h:form id="frm">
			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:button value="Novo" />
					<p:commandButton value="Salvar" id="botaoSalvar"
						action="#{cadastroLancamentoBean.salvar}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Pesquisa"
						outcome="/financeiro/PesquisaLancamentos" />
				</p:toolbarGroup>
			</p:toolbar>
			<p:messages showDetail="false" showSummary="true" autoUpdate="true" />

			<p:panelGrid style="margin-top: 20px" columns="2" id="grid">

				<p:outputLabel value="Tipo" for="tipo" />
				<p:selectOneButton id="tipo"
					value="#{cadastroLancamentoBean.lancamento.tipo}">
					<f:selectItems value="#{cadastroLancamentoBean.tiposLancamentos}"
						var="tipoLancamento" itemValue="#{tipoLancamento}"
						itemLabel="#{tipoLancamento.descricao}" />
				</p:selectOneButton>


				<p:notificationBar position="top" effect="slide" styleClass="top"
					widgetVar="bar">
					<h:outputText value="PrimeFaces Rocks!" style="font-size:36px;" />
				</p:notificationBar>

				<p:commandButton value="Show" onclick="PF('bar').show()"
					type="button" icon="ui-icon-arrow-1-s" />
				<p:commandButton value="Hide" onclick="PF('bar').hide()"
					type="button" icon="ui-icon-arrow-1-n" />
					
					<p:outputLabel value="Nome" for="nome" widgetVar="bar" process="@this" />
				<p:inputText id="nome" size="60" maxlength="80"/>	

				<h:outputLabel />
				<p:commandButton value="Salvar"
					action="#{cadastroLancamentoBean.salvar}" icon="ui-icon-disk"
					update="@form" />
			</p:panelGrid>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/financeiro/PesquisaCentroDeCusto.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/Layout.xhtml">

	<ui:define name="content">

		<h:form id="frmPesquisa">
			<h1>Pesquisa Centro de Custo</h1>

			<p:messages autoUpdate="true" closable="true" />

			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:commandButton value="Pesquisar"
						action="#{pesquisaCustosBean.custosList}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Novo" outcome="/financeiro/CadastroCentroDeCusto" />
				</p:toolbarGroup>
			</p:toolbar>

			<p:dataTable id="custosTable"
				value="#{pesquisaCustosBean.custosList}" var="custo"
				style="margin-top: 20px" emptyMessage="Nenhum custo encontrado."
				rows="20" paginator="true" paginatorAlwaysVisible="false"
				paginatorPosition="bottom">

				<p:column headerText="Nome">
					<h:outputText value="#{custo.nome}" />
				</p:column>


				<p:column style="width: 100px; text-align: center">
					<p:button outcome="/financeiro/CadastroCentroDeCusto" icon="ui-icon-pencil"
						title="Editar">
						<f:param name="custo" value="#{custo.id}" />
					</p:button>
					<p:commandButton icon="ui-icon-trash" title="Excluir"
						oncomplete="confirmacaoExclusao.show()" />
				</p:column>

			</p:dataTable>

		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/financeiro/PesquisaLancamentos.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/Layout.xhtml">

	<ui:define name="content">

		<f:metadata>
			<f:viewAction action="#{pesquisaLancamentosBean.consultar}" />
		</f:metadata>

		<h:form id="frm">

			<h1>Pesquisa Lançamentos</h1>


			<p:toolbar style="margin-top: 20px">

				<p:toolbarGroup align="right">
					<p:button value="Novo" outcome="/financeiro/CadastroLancamento" />
				</p:toolbarGroup>
			</p:toolbar>

			<p:messages showDetail="false" showSummary="true" autoUpdate="true" />

			<p:dataTable id="tbl" style="margin-top: 20px; margin-bottom: 10px"
				value="#{pesquisaLancamentosBean.lancamentos}" var="lancamento"
				border="1" cellspacing="0" cellpadding="2" paginator="true" rows="5"
				paginatorPosition="bottom">

				<p:column filterBy="#{lancamento.id}" headerText="Código"
					filterMatchMode="contains">
					<h:outputText value="#{lancamento.id}" />
				</p:column>

				<p:column filterBy="#{lancamento.tipo.descricao}" headerText="Tipo"
					filterMatchMode="contains">
					<h:outputText value="#{lancamento.tipo.descricao}" />
				</p:column>

				<p:column filterBy="#{lancamento.statusPagamento.descricao}"
					headerText="Status" filterMatchMode="contains">
					<h:outputText value="#{lancamento.statusPagamento.descricao}" />
				</p:column>

				<p:column filterBy="#{lancamento.pessoa.nome}" headerText="Pessoa"
					filterMatchMode="contains">
					<h:outputText value="#{lancamento.pessoa.nome}" />
				</p:column>

				<p:column filterBy="#{lancamento.custo.nome}" headerText="Custo"
					filterMatchMode="contains">
					<h:outputText value="#{lancamento.custo.nome}" />
				</p:column>

				<p:column filterBy="#{lancamento.descricao}" headerText="Descrição"
					filterMatchMode="contains">
					<h:outputText value="#{lancamento.descricao}" />
				</p:column>


				<p:column filterBy="#{lancamento.valorPago}" headerText="Valor Pg"
					filterMatchMode="contains">
					<h:outputText value="#{lancamento.valorPago}">
						<f:convertNumber type="currency" locale="pt_BR" />
					</h:outputText>
				</p:column>
				
				<p:column filterBy="#{lancamento.valorRecebido}" headerText="Valor Rec."
					filterMatchMode="contains">
					<h:outputText value="#{lancamento.valorRecebido}">
						<f:convertNumber type="currency" locale="pt_BR" />
					</h:outputText>
				</p:column>


				<p:column headerText="Vencimento" style="text-align: center"
					sortBy="#{lancamento.dataVencimento}" width="100">
					<h:outputText value="#{lancamento.dataVencimento}">
						<f:convertDateTime pattern="dd/MM/yyyy"
							timeZone="America/Sao_Paulo" />
					</h:outputText>
				</p:column>

				<p:column width="70" style="text-align: center">
					<p:button icon="ui-icon-pencil" title="Editar"
						outcome="/financeiro/CadastroLancamento">
						<f:param name="id" value="#{lancamento.id}" />
					</p:button>

				</p:column>

				
			</p:dataTable>
			
			<p:dataTable>
			 <p:columnGroup type="footer">
					<p:row>
						<p:column colspan="6" style="text-align:right"
							footerText="Total Geral:" />
						<p:column footerText="R$#{pesquisaLancamentosBean.valorTotalPago()}" />
						<p:column footerText="R$#{pesquisaLancamentosBean.valorTotalRecebido()}"/>
					</p:row>
				</p:columnGroup>
			</p:dataTable>	

			<h:commandLink id="excel">

				<p:graphicImage library="reobotnet" name="images/excel.png" />
				<p:dataExporter type="xls" target="tbl" fileName="Lançamentos"
					postProcessor="#{customizedDocumentsView.postProcessXLS}" />
			</h:commandLink>

			<h:commandLink id="pdf">
				<p:graphicImage name="/demo/images/pdf.png" />
				<p:dataExporter type="pdf" target="tbl" fileName="L"
					preProcessor="#{customizedDocumentsView.preProcessPDF}" />
			</h:commandLink>
		</h:form>

	</ui:define>
</ui:composition>